import type { Review } from "@/components/app/ReviewFeed";

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    author: "James T.",
    platform: "Google",
    rating: 5,
    body: "Arctic Air came out the same day our AC died in the middle of a Texas heat wave. Technician was professional, diagnosed the issue in 20 minutes, and had us cooling again within the hour. Pricing was fair and transparent — no surprise fees. Will absolutely call them again.",
    date: "2026-04-28",
    sentiment: "positive",
    replied: false,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r2",
    author: "Maria G.",
    platform: "Google",
    rating: 5,
    body: "Hands down the best HVAC company in Dallas. They installed a new Carrier system for us and the crew was clean, on-time, and finished ahead of schedule. Our energy bill dropped noticeably the first month. Highly recommend for any HVAC work.",
    date: "2026-04-22",
    sentiment: "positive",
    replied: true,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r3",
    author: "Robert K.",
    platform: "Yelp",
    rating: 4,
    body: "Good service overall. The technician was knowledgeable and explained what was wrong with my heat pump clearly. Took a little longer than quoted to get the part, but they kept me updated throughout. Would use again.",
    date: "2026-04-18",
    sentiment: "positive",
    replied: false,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r4",
    author: "Sandra L.",
    platform: "Google",
    rating: 3,
    body: "Service was fine, technician was polite. The repair fixed the problem but the scheduling was a bit disorganized — I had to call twice to confirm my appointment window. Nothing terrible but there's room to improve on the customer service side.",
    date: "2026-04-15",
    sentiment: "neutral",
    replied: false,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r5",
    author: "David P.",
    platform: "Google",
    rating: 5,
    body: "I've used Arctic Air three times now — twice for AC maintenance and once for an emergency heat call. Every single time has been a great experience. These guys are honest, which is rare. They told me my system had another 3-4 years left instead of pushing a replacement. That kind of integrity earns loyalty.",
    date: "2026-04-10",
    sentiment: "positive",
    replied: true,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r6",
    author: "Linda H.",
    platform: "Google",
    rating: 1,
    body: "Very disappointed. Paid $320 for a repair that failed again within two weeks. When I called back, I was told I'd need to pay for another service call to diagnose it again. No warranty on the work? That's unacceptable. I had to call a different company to actually fix it.",
    date: "2026-04-05",
    sentiment: "negative",
    replied: false,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r7",
    author: "Carlos M.",
    platform: "Google",
    rating: 5,
    body: "Fast, professional, and reasonably priced. Needed my annual AC tune-up before summer and they got me in within two days. Technician was thorough and found a small refrigerant issue before it became a big problem. This is the kind of proactive service that saves you money long term.",
    date: "2026-03-30",
    sentiment: "positive",
    replied: false,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r8",
    author: "Patricia W.",
    platform: "Yelp",
    rating: 2,
    body: "Scheduling was a nightmare. Had to reschedule twice because the technician didn't show up during the promised window. The actual repair once someone did come was OK, but the experience getting there was frustrating enough that I won't be using them again.",
    date: "2026-03-22",
    sentiment: "negative",
    replied: false,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r9",
    author: "Brian A.",
    platform: "Google",
    rating: 4,
    body: "Solid company. They replaced our entire ductwork system and the results are noticeable — better airflow in all rooms, and quieter too. Took two full days as expected. Minor issue with a vent cover was fixed on the spot when I pointed it out. Good communication throughout.",
    date: "2026-03-15",
    sentiment: "positive",
    replied: true,
    businessName: "Arctic Air HVAC Services",
  },
  {
    id: "r10",
    author: "Theresa N.",
    platform: "Facebook",
    rating: 5,
    body: "Called Arctic Air on a Friday evening when our furnace stopped working. They sent someone out Saturday morning and had it running by noon. In January. I cannot overstate how grateful we were. The technician even walked me through what caused the failure so I know what to watch for. 10/10.",
    date: "2026-03-08",
    sentiment: "positive",
    replied: true,
    businessName: "Arctic Air HVAC Services",
  },
];
